worker-threads: 4
worker-fs-threads: 2
worker-grpc-threads: 2
logger-level: info

is-testing: false

server-port: 8080
server-grpc-port: 8081

hello-endpoint: '[::1]:8081'

dbconnection: 'postgresql://SI-plus-plus-game_user:password@localhost:5432/SI-plus-plus-game_db_1'
